export const advantageList = [
  {
    number: '1',
    title: 'card-title-1',
    description: 'card-description-1',
    titleColor: '#000',
    descriptionColor: '#000',
    numberColor: '#000',
    backgroundColor: '#fff',
    hasBorder: false,
  },
  {
    number: '2',
    title: 'card-title-2',
    description: 'card-description-2',
    titleColor: '#FFF',
    descriptionColor: '#FFF',
    numberColor: '#FFF',
    backgroundColor: '#222624',
    hasBorder: true,
  },
  {
    number: '3',
    title: 'card-title-3',
    description: 'card-description-3',
    titleColor: '#FFF',
    descriptionColor: '#FFF',
    numberColor: '#FFF',
    backgroundColor: '#0D6466',
    hasBorder: false,
  },
  {
    number: '4',
    title: 'card-title-4',
    description: 'card-description-4',
    titleColor: '#000',
    descriptionColor: '#000',
    numberColor: '#000',
    backgroundColor: '#fff',
    hasBorder: false,
  },
]
