export const advantageList = [
  {
    number: '1',
    title: 'без ограничений и скучных конструкторов',
    description: 'Создаем сайты с гибким кодом и высокой скоростью загрузки, избегая шаблонов.',
    titleColor: '#000',
    descriptionColor: '#000',
    numberColor: '#000',
    backgroundColor: '#fff',
    hasBorder: false,
  },
  {
    number: '2',
    title: '100+ крутых проектов в портфолио',
    description: 'За 5 лет мы реализовали более 100 проектов, решая задачи бизнеса в разных нишах и находя лучшие решения для каждого клиента.',
    titleColor: '#FFF',
    descriptionColor: '#FFF',
    numberColor: '#FFF',
    backgroundColor: '#222624',
    hasBorder: true,
  },
  {
    number: '3',
    title: 'Моментальная загрузка без потери клиентов',
    description: 'Сайт загружается менее 1 секунды — это значит больше клиентов и заявок без потерь из-за медленного отклика.',
    titleColor: '#FFF',
    descriptionColor: '#FFF',
    numberColor: '#FFF',
    backgroundColor: '#0D6466',
    hasBorder: false,
  },
  {
    number: '4',
    title: 'Простая админка — редактируйте сами',
    description: 'Мы настраиваем удобную админ-панель, позволяющую легко управлять страницами, редактировать тексты и обновлять изображения всего в пару кликов.',
    titleColor: '#000',
    descriptionColor: '#000',
    numberColor: '#000',
    backgroundColor: '#fff',
    hasBorder: false,
  },
]
