export const marketingCard = [
  {
    title: 'МАРКЕТИНГОВЫЙ АНАЛИЗ',
    description: 'Изучаем вашу компанию и продукт, проводим анализ целевой аудитории и конкурентов. Вместе определяем цели сайта, ключевые функции и структуру, чтобы он точно работал на ваш результат.',
    colorTitle: '#000',
    colorDescription: '#000',
    backgroundColor: '#FFF',
    topBtn: '/svg/bool-1.svg ',
    hasBorder: false,
  },
  {
    title: 'Разработка прототипа',
    description: 'Разрабатываем логичную схему сайта, чтобы пользователям было удобно. Делаем интерактивные прототипы страниц — вы сразу видите, как будет выглядеть сайт, ещё до дизайна.',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    backgroundColor: '#222624',
    topBtn: '/svg/bool-2.svg ',
    hasBorder: true,
  },
  {
    title: 'UX/UI Дизайн',
    description: 'Создаём не шаблонный, а индивидуальный дизайн, который отражает ваш бренд, вызывает доверие и вовлекает клиентов',
    colorTitle: '#000',
    colorDescription: '#000',
    backgroundColor: '#FFF ',
    topBtn: '/svg/bool-1.svg ',
    hasBorder: false,
    backgroundImg: '/img/marketing-1.png',
  },
  {
    title: 'Создание сайта',
    description: 'Создаем быстрые и адаптивные сайты с оптимизированной скоростью загрузки (90%-100%), которые работают без сбоев. Никаких конструкторов — полная свобода в функционале и дизайне.',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    backgroundColor: '#0D6466',
    topBtn: '/svg/bool-2.svg ',
    hasBorder: false,
  },
  {
    title: 'Интеграции и запуск',
    description: 'Внедряем аналитику, CRM и платёжные системы. Проводим финальные проверки и запускаем сайт, готовый приносить заказы и решать ваши бизнес-задачи.',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    backgroundColor: '#222624 ',
    topBtn: '/svg/bool-2.svg ',
    hasBorder: true,
    backgroundImg: '/img/marketing-2.png',
  },
]