export const marketingCard = [
  {
    title: 'card-title-1',
    description: 'card-description-1',
    colorTitle: '#000',
    colorDescription: '#000',
    backgroundColor: '#FFF',
    topBtn: '/svg/bool-1.svg ',
    hasBorder: false,
  },
  {
    title: 'card-title-2',
    description: 'card-description-2',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    backgroundColor: '#222624',
    topBtn: '/svg/bool-2.svg ',
    hasBorder: true,
  },
  {
    title: 'card-title-3',
    description: 'card-description-3',
    colorTitle: '#000',
    colorDescription: '#000',
    backgroundColor: '#FFF ',
    topBtn: '/svg/bool-1.svg ',
    hasBorder: false,
    backgroundImg: '/img/marketing-1.webp',
  },
  {
    title: 'card-title-4',
    description: 'card-description-4',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    backgroundColor: '#0D6466',
    topBtn: '/svg/bool-2.svg ',
    hasBorder: false,
  },
  {
    title: 'card-title-5',
    description: 'card-description-5',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    backgroundColor: '#222624 ',
    topBtn: '/svg/bool-2.svg ',
    hasBorder: true,
    backgroundImg: '/img/marketing-2.webp',
  },
]