export const typesList = [
  {
    img: '/img/types-stie-1.webp',
    imgClass: 'img-1',
    title: 'card-title-1',
    description: 'card-description-1',
    price: 'от 20 000₽',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    colorPrice: '#FFF',
    backgroundColor: '#222624',
    backgroundBtnBorder: '1px solid #FFF',
    colorBtn: '#FFF',
  },
  {
    img: '/img/types-stie-2.webp',
    img1086: '/img/types-stie-2-1086.webp',
    imgClass: 'img-2',
    title: 'card-title-2',
    description: 'card-description-2',
    price: 'от 45 000₽',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    colorPrice: '#FFF',
    backgroundColor: '#0D6466',
    backgroundBtnBorder: '1px solid #FFF',
    colorBtn: '#FFF', 
  },
  {
    title: 'card-title-3',
    description: 'card-description-3',
    price: 'от 29 000₽',
    colorTitle: '#000',
    colorDescription: '#000',
    colorPrice: '#000',
    backgroundColor: '#FFCB9B',
    backgroundBtnBorder: '1px solid #000',
    colorBtn: '#000',
  },
  {
    img: '/img/types-stie-3.webp',
    img1086: '/img/types-stie-3-1086.webp',
    imgClass: 'img-3',
    title: 'card-title-4',
    description: 'card-description-4',
    price: 'от 5 000₽',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    colorPrice: '#FFF',
    backgroundColor: '#0D6466',
    backgroundBtnBorder: '1px solid #FFF',
    colorBtn: '#FFF',
  }
]
