export const typesList = [
  {
    img: '/img/types-stie-1.webp',
    imgClass: 'img-1',
    title: 'Лендинг',
    description: 'Простой и эффективный сайт для быстрого представления вашего продукта или услуги, с фокусом на конверсии и привлечении клиентов.',
    price: 'от 30 000₽',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    colorPrice: '#FFF',
    backgroundColor: '#222624',
    backgroundBtnBorder: '1px solid #FFF',
    colorBtn: '#FFF',
  },
  {
    img: '/img/types-stie-2.webp',
    img1086: '/img/types-stie-2-1086.webp',
    imgClass: 'img-2',
    title: 'ИНТЕРНЕТ-МАГАЗИН',
    description: 'Полноценный интернет-магазин для продажи товаров онлайн. Удобный интерфейс для покупателей и простота в управлении для вас.',
    price: 'от 80 000₽',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    colorPrice: '#FFF',
    backgroundColor: '#0D6466',
    backgroundBtnBorder: '1px solid #FFF',
    colorBtn: '#FFF', 
  },
  {
    title: 'Корпоративный сайт',
    description: 'Сайт для вашей компании, который поможет представить бизнес и его услуги в интернете, с понятной навигацией и современным дизайном.',
    price: 'от 50 000₽',
    colorTitle: '#000',
    colorDescription: '#000',
    colorPrice: '#000',
    backgroundColor: '#FFCB9B',
    backgroundBtnBorder: '1px solid #000',
    colorBtn: '#000',
  },
  {
    img: '/img/types-stie-3.webp',
    img1086: '/img/types-stie-3-1086.webp',
    imgClass: 'img-3',
    title: 'Дизайн',
    description: 'Профессиональный дизайн вашего сайта',
    price: 'от 5 000₽',
    colorTitle: '#FFF',
    colorDescription: '#FFF',
    colorPrice: '#FFF',
    backgroundColor: '#0D6466',
    backgroundBtnBorder: '1px solid #FFF',
    colorBtn: '#FFF',
  }
]
